name: Build Cordova APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Cordova CLI
      run: npm install -g cordova

    - name: Install project dependencies
      run: npm install

    - name: Add Android platform
      run: cordova platform add android

    - name: Make gradlew executable
      run: chmod +x platforms/android/gradlew

    - name: Build APK
      run: cd platforms/android && ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: E-Leak-debug-apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
